-- scripts/lib/linguist.lua: GENERATED from GitHub Linguist languages.yml; do not edit by hand.
-- Regenerate with scripts/gen-linguist.lua (see its header).

return {
  ["1c enterprise"] = { t = "programming", c = "#814CCC" },
  ["2-dimensional array"] = { t = "data", c = "#38761D" },
  ["4d"] = { t = "programming", c = "#004289" },
  ["abap"] = { t = "programming", c = "#E8274B" },
  ["abap cds"] = { t = "programming", c = "#555e25" },
  ["abnf"] = { t = "data" },
  ["ags script"] = { t = "programming", c = "#B9D9FF" },
  ["aidl"] = { t = "programming", c = "#34EB6B" },
  ["al"] = { t = "programming", c = "#3AA2B5" },
  ["algol"] = { t = "programming", c = "#D1E0DB" },
  ["ampl"] = { t = "programming", c = "#E6EFBB" },
  ["antlr"] = { t = "programming", c = "#9DC3FF" },
  ["api blueprint"] = { t = "markup", c = "#2ACCA8" },
  ["apl"] = { t = "programming", c = "#5A8164" },
  ["asl"] = { t = "programming" },
  ["asn.1"] = { t = "data" },
  ["asp.net"] = { t = "programming", c = "#9400ff" },
  ["ats"] = { t = "programming", c = "#1ac620" },
  ["actionscript"] = { t = "programming", c = "#882B0F" },
  ["ada"] = { t = "programming", c = "#02f88c" },
  ["adblock filter list"] = { t = "data", c = "#800000" },
  ["adobe font metrics"] = { t = "data", c = "#fa0f00" },
  ["agda"] = { t = "programming", c = "#315665" },
  ["aiken"] = { t = "programming", c = "#640ff8" },
  ["alloy"] = { t = "programming", c = "#64C800" },
  ["alpine abuild"] = { t = "programming", c = "#0D597F" },
  ["altium designer"] = { t = "data", c = "#A89663" },
  ["angelscript"] = { t = "programming", c = "#C7D7DC" },
  ["answer set programming"] = { t = "programming", c = "#A9CC29" },
  ["ant build system"] = { t = "data", c = "#A9157E" },
  ["antlers"] = { t = "markup", c = "#ff269e" },
  ["apacheconf"] = { t = "data", c = "#d12127" },
  ["apex"] = { t = "programming", c = "#1797c0" },
  ["apollo guidance computer"] = { t = "programming", c = "#0B3D91" },
  ["applescript"] = { t = "programming", c = "#101F1F" },
  ["arc"] = { t = "programming", c = "#aa2afe" },
  ["asciidoc"] = { t = "prose", c = "#73a0c5" },
  ["aspectj"] = { t = "programming", c = "#a957b0" },
  ["assembly"] = { t = "programming", c = "#6E4C13" },
  ["astro"] = { t = "markup", c = "#ff5a03" },
  ["asymptote"] = { t = "programming", c = "#ff0000" },
  ["augeas"] = { t = "programming", c = "#9CC134" },
  ["autohotkey"] = { t = "programming", c = "#6594b9" },
  ["autoit"] = { t = "programming", c = "#1C3552" },
  ["avro idl"] = { t = "data", c = "#0040FF" },
  ["awk"] = { t = "programming", c = "#c30e9b" },
  ["b (formal method)"] = { t = "programming", c = "#8aa8c5" },
  ["b4x"] = { t = "programming", c = "#00e4ff" },
  ["baml"] = { t = "programming", c = "#a855f7" },
  ["basic"] = { t = "programming", c = "#ff0000" },
  ["bqn"] = { t = "programming", c = "#2b7067" },
  ["ballerina"] = { t = "programming", c = "#FF5000" },
  ["batchfile"] = { t = "programming", c = "#C1F12E" },
  ["beef"] = { t = "programming", c = "#a52f4e" },
  ["befunge"] = { t = "programming" },
  ["berry"] = { t = "programming", c = "#15A13C" },
  ["bibtex"] = { t = "markup", c = "#778899" },
  ["bibtex style"] = { t = "programming" },
  ["bicep"] = { t = "programming", c = "#519aba" },
  ["bikeshed"] = { t = "markup", c = "#5562ac" },
  ["bison"] = { t = "programming", c = "#6A463F" },
  ["bitbake"] = { t = "programming", c = "#00bce4" },
  ["blade"] = { t = "markup", c = "#f7523f" },
  ["blitzbasic"] = { t = "programming", c = "#00FFAE" },
  ["blitzmax"] = { t = "programming", c = "#cd6400" },
  ["bluespec"] = { t = "programming", c = "#12223c" },
  ["bluespec bh"] = { t = "programming", c = "#12223c" },
  ["boo"] = { t = "programming", c = "#d4bec1" },
  ["boogie"] = { t = "programming", c = "#c80fa0" },
  ["brainfuck"] = { t = "programming", c = "#2F2530" },
  ["brighterscript"] = { t = "programming", c = "#66AABB" },
  ["brightscript"] = { t = "programming", c = "#662D91" },
  ["browserslist"] = { t = "data", c = "#ffd539" },
  ["bru"] = { t = "markup", c = "#F4AA41" },
  ["buildstream"] = { t = "data", c = "#006bff" },
  ["c"] = { t = "programming", c = "#555555" },
  ["c#"] = { t = "programming", c = "#178600" },
  ["c++"] = { t = "programming", c = "#f34b7d" },
  ["c-objdump"] = { t = "data" },
  ["c2hs haskell"] = { t = "programming" },
  ["c3"] = { t = "programming", c = "#2563eb" },
  ["cap cds"] = { t = "programming", c = "#0092d1" },
  ["cil"] = { t = "data" },
  ["clips"] = { t = "programming", c = "#00A300" },
  ["cmake"] = { t = "programming", c = "#DA3434" },
  ["cobol"] = { t = "programming" },
  ["codeowners"] = { t = "data" },
  ["collada"] = { t = "data", c = "#F1A42B" },
  ["cql"] = { t = "programming", c = "#006091" },
  ["cson"] = { t = "data", c = "#244776" },
  ["css"] = { t = "markup", c = "#663399" },
  ["csv"] = { t = "data", c = "#237346" },
  ["cue"] = { t = "programming", c = "#5886E1" },
  ["cweb"] = { t = "programming", c = "#00007a" },
  ["cabal config"] = { t = "data", c = "#483465" },
  ["caddyfile"] = { t = "data", c = "#22b638" },
  ["cadence"] = { t = "programming", c = "#00ef8b" },
  ["cairo"] = { t = "programming", c = "#ff4a48" },
  ["cairo zero"] = { t = "programming", c = "#ff4a48" },
  ["cameligo"] = { t = "programming", c = "#3be133" },
  ["cangjie"] = { t = "programming", c = "#00868B" },
  ["cap'n proto"] = { t = "programming", c = "#c42727" },
  ["carbon"] = { t = "programming", c = "#222222" },
  ["cartocss"] = { t = "programming" },
  ["ceylon"] = { t = "programming", c = "#dfa535" },
  ["chapel"] = { t = "programming", c = "#8dc63f" },
  ["charity"] = { t = "programming" },
  ["checksums"] = { t = "data" },
  ["chuck"] = { t = "programming", c = "#3f8000" },
  ["circom"] = { t = "programming", c = "#707575" },
  ["cirru"] = { t = "programming", c = "#ccccff" },
  ["clarion"] = { t = "programming", c = "#db901e" },
  ["clarity"] = { t = "programming", c = "#5546ff" },
  ["classic asp"] = { t = "programming", c = "#6a40fd" },
  ["clean"] = { t = "programming", c = "#3F85AF" },
  ["click"] = { t = "programming", c = "#E4E6F3" },
  ["clojure"] = { t = "programming", c = "#db5855" },
  ["closure templates"] = { t = "markup", c = "#0d948f" },
  ["cloud firestore security rules"] = { t = "data", c = "#FFA000" },
  ["clue"] = { t = "programming", c = "#0009b5" },
  ["conll-u"] = { t = "data" },
  ["codeql"] = { t = "programming", c = "#140f46" },
  ["coffeescript"] = { t = "programming", c = "#244776" },
  ["coldfusion"] = { t = "programming", c = "#ed2cd6" },
  ["coldfusion cfc"] = { t = "programming", c = "#ed2cd6" },
  ["common lisp"] = { t = "programming", c = "#3fb68b" },
  ["common workflow language"] = { t = "programming", c = "#B5314C" },
  ["component pascal"] = { t = "programming", c = "#B0CE4E" },
  ["cooklang"] = { t = "markup", c = "#E15A29" },
  ["cool"] = { t = "programming" },
  ["cpp-objdump"] = { t = "data" },
  ["creole"] = { t = "prose" },
  ["crystal"] = { t = "programming", c = "#000100" },
  ["csound"] = { t = "programming", c = "#1a1a1a" },
  ["csound document"] = { t = "programming", c = "#1a1a1a" },
  ["csound score"] = { t = "programming", c = "#1a1a1a" },
  ["cuda"] = { t = "programming", c = "#3A4E3A" },
  ["cue sheet"] = { t = "data" },
  ["curry"] = { t = "programming", c = "#531242" },
  ["cycript"] = { t = "programming" },
  ["cylc"] = { t = "data", c = "#00b3fd" },
  ["cypher"] = { t = "programming", c = "#34c0eb" },
  ["cython"] = { t = "programming", c = "#fedf5b" },
  ["d"] = { t = "programming", c = "#ba595e" },
  ["d-objdump"] = { t = "data" },
  ["d2"] = { t = "markup", c = "#526ee8" },
  ["digital command language"] = { t = "programming" },
  ["dm"] = { t = "programming", c = "#447265" },
  ["dns zone"] = { t = "data" },
  ["dtrace"] = { t = "programming" },
  ["dafny"] = { t = "programming", c = "#FFEC25" },
  ["darcs patch"] = { t = "data", c = "#8eff23" },
  ["dart"] = { t = "programming", c = "#00B4AB" },
  ["daslang"] = { t = "programming", c = "#d3d3d3" },
  ["dataweave"] = { t = "programming", c = "#003a52" },
  ["debian package control file"] = { t = "data", c = "#D70751" },
  ["denizenscript"] = { t = "programming", c = "#FBEE96" },
  ["dhall"] = { t = "programming", c = "#dfafff" },
  ["diff"] = { t = "data" },
  ["directx 3d file"] = { t = "data", c = "#aace60" },
  ["dockerfile"] = { t = "programming", c = "#384d54" },
  ["dogescript"] = { t = "programming", c = "#cca760" },
  ["dotenv"] = { t = "data", c = "#e5d559" },
  ["dune"] = { t = "programming", c = "#89421e" },
  ["dylan"] = { t = "programming", c = "#6c616e" },
  ["e"] = { t = "programming", c = "#ccce35" },
  ["e-mail"] = { t = "data" },
  ["ebnf"] = { t = "data" },
  ["ecl"] = { t = "programming", c = "#8a1267" },
  ["eclipse"] = { t = "programming", c = "#001d9d" },
  ["ejs"] = { t = "markup", c = "#a91e50" },
  ["eq"] = { t = "programming", c = "#a78649" },
  ["eagle"] = { t = "data" },
  ["earthly"] = { t = "programming", c = "#2af0ff" },
  ["easybuild"] = { t = "data", c = "#069406" },
  ["ecere projects"] = { t = "data", c = "#913960" },
  ["ecmarkup"] = { t = "markup", c = "#eb8131" },
  ["edge"] = { t = "markup", c = "#0dffe0" },
  ["edgeql"] = { t = "programming", c = "#31A7FF" },
  ["editorconfig"] = { t = "data", c = "#fff1f2" },
  ["edje data collection"] = { t = "data" },
  ["eiffel"] = { t = "programming", c = "#4d6977" },
  ["elixir"] = { t = "programming", c = "#6e4a7e" },
  ["elm"] = { t = "programming", c = "#60B5CC" },
  ["elvish"] = { t = "programming", c = "#55BB55" },
  ["elvish transcript"] = { t = "programming", c = "#55BB55" },
  ["emacs lisp"] = { t = "programming", c = "#c065db" },
  ["emberscript"] = { t = "programming", c = "#FFF4F3" },
  ["erlang"] = { t = "programming", c = "#B83998" },
  ["euphoria"] = { t = "programming", c = "#FF790B" },
  ["f#"] = { t = "programming", c = "#b845fc" },
  ["f*"] = { t = "programming", c = "#572e30" },
  ["figlet font"] = { t = "data", c = "#FFDDBB" },
  ["firrtl"] = { t = "programming", c = "#2f632f" },
  ["flux"] = { t = "programming", c = "#88ccff" },
  ["factor"] = { t = "programming", c = "#636746" },
  ["fancy"] = { t = "programming", c = "#7b9db4" },
  ["fantom"] = { t = "programming", c = "#14253c" },
  ["faust"] = { t = "programming", c = "#c37240" },
  ["fennel"] = { t = "programming", c = "#fff3d7" },
  ["filebench wml"] = { t = "programming", c = "#F6B900" },
  ["filterscript"] = { t = "programming" },
  ["flatbuffers"] = { t = "data", c = "#ed284a" },
  ["flix"] = { t = "programming", c = "#d44a45" },
  ["fluent"] = { t = "programming", c = "#ffcc33" },
  ["formatted"] = { t = "data" },
  ["forth"] = { t = "programming", c = "#341708" },
  ["fortran"] = { t = "programming", c = "#4d41b1" },
  ["fortran free form"] = { t = "programming", c = "#4d41b1" },
  ["freebasic"] = { t = "programming", c = "#141AC9" },
  ["freemarker"] = { t = "programming", c = "#0050b2" },
  ["frege"] = { t = "programming", c = "#00cafe" },
  ["futhark"] = { t = "programming", c = "#5f021f" },
  ["g-code"] = { t = "programming", c = "#D08CF2" },
  ["gaml"] = { t = "programming", c = "#FFC766" },
  ["gams"] = { t = "programming", c = "#f49a22" },
  ["gap"] = { t = "programming", c = "#0000cc" },
  ["gcc machine description"] = { t = "programming", c = "#FFCFAB" },
  ["gdb"] = { t = "programming" },
  ["gdscript"] = { t = "programming", c = "#355570" },
  ["gdshader"] = { t = "programming", c = "#478CBF" },
  ["gedcom"] = { t = "data", c = "#003058" },
  ["glsl"] = { t = "programming", c = "#5686a5" },
  ["gn"] = { t = "data" },
  ["gsc"] = { t = "programming", c = "#FF6800" },
  ["game maker language"] = { t = "programming", c = "#71b417" },
  ["gemfile.lock"] = { t = "data", c = "#701516" },
  ["gemini"] = { t = "prose", c = "#ff6900" },
  ["genero 4gl"] = { t = "programming", c = "#63408e" },
  ["genero per"] = { t = "markup", c = "#d8df39" },
  ["genie"] = { t = "programming", c = "#fb855d" },
  ["genshi"] = { t = "programming", c = "#951531" },
  ["gentoo ebuild"] = { t = "programming", c = "#9400ff" },
  ["gentoo eclass"] = { t = "programming", c = "#9400ff" },
  ["gerber image"] = { t = "data", c = "#d20b00" },
  ["gettext catalog"] = { t = "prose" },
  ["gherkin"] = { t = "programming", c = "#5B2063" },
  ["git attributes"] = { t = "data", c = "#F44D27" },
  ["git commit"] = { t = "data", c = "#F44D27" },
  ["git config"] = { t = "data", c = "#F44D27" },
  ["git revision list"] = { t = "data", c = "#F44D27" },
  ["gleam"] = { t = "programming", c = "#ffaff3" },
  ["glimmer js"] = { t = "programming", c = "#F5835F" },
  ["glimmer ts"] = { t = "programming", c = "#3178c6" },
  ["glyph"] = { t = "programming", c = "#c1ac7f" },
  ["glyph bitmap distribution format"] = { t = "data" },
  ["gnuplot"] = { t = "programming", c = "#f0a9f0" },
  ["go"] = { t = "programming", c = "#00ADD8" },
  ["go checksums"] = { t = "data", c = "#00ADD8" },
  ["go module"] = { t = "data", c = "#00ADD8" },
  ["go template"] = { t = "markup", c = "#00ADD8" },
  ["go workspace"] = { t = "data", c = "#00ADD8" },
  ["godot resource"] = { t = "data", c = "#355570" },
  ["golo"] = { t = "programming", c = "#88562A" },
  ["gosu"] = { t = "programming", c = "#82937f" },
  ["grace"] = { t = "programming", c = "#615f8b" },
  ["gradle"] = { t = "data", c = "#02303a" },
  ["gradle kotlin dsl"] = { t = "data", c = "#02303a" },
  ["grammatical framework"] = { t = "programming", c = "#ff0000" },
  ["graph modeling language"] = { t = "data" },
  ["graphql"] = { t = "data", c = "#e10098" },
  ["graphviz (dot)"] = { t = "data", c = "#2596be" },
  ["groovy"] = { t = "programming", c = "#4298b8" },
  ["groovy server pages"] = { t = "programming", c = "#4298b8" },
  ["haproxy"] = { t = "data", c = "#106da9" },
  ["hcl"] = { t = "programming", c = "#844FBA" },
  ["hip"] = { t = "programming", c = "#4F3A4F" },
  ["hlsl"] = { t = "programming", c = "#aace60" },
  ["hocon"] = { t = "data", c = "#9ff8ee" },
  ["html"] = { t = "markup", c = "#e34c26" },
  ["html+ecr"] = { t = "markup", c = "#2e1052" },
  ["html+eex"] = { t = "markup", c = "#6e4a7e" },
  ["html+erb"] = { t = "markup", c = "#701516" },
  ["html+php"] = { t = "markup", c = "#4f5d95" },
  ["html+razor"] = { t = "markup", c = "#512be4" },
  ["http"] = { t = "data", c = "#005C9C" },
  ["hxml"] = { t = "data", c = "#f68712" },
  ["hack"] = { t = "programming", c = "#878787" },
  ["haml"] = { t = "markup", c = "#ece2a9" },
  ["handlebars"] = { t = "markup", c = "#f7931e" },
  ["harbour"] = { t = "programming", c = "#0e60e3" },
  ["hare"] = { t = "programming", c = "#9d7424" },
  ["haskell"] = { t = "programming", c = "#5e5086" },
  ["haxe"] = { t = "programming", c = "#df7900" },
  ["hiveql"] = { t = "programming", c = "#dce200" },
  ["holyc"] = { t = "programming", c = "#ffefaf" },
  ["hosts file"] = { t = "data", c = "#308888" },
  ["hurl"] = { t = "programming", c = "#FF0288" },
  ["hy"] = { t = "programming", c = "#7790B2" },
  ["hyphy"] = { t = "programming" },
  ["idl"] = { t = "programming", c = "#a3522f" },
  ["igor pro"] = { t = "programming", c = "#0000cc" },
  ["il assembly"] = { t = "programming", c = "#512BD4" },
  ["ini"] = { t = "data", c = "#d1dbe0" },
  ["irc log"] = { t = "data" },
  ["ispc"] = { t = "programming", c = "#2D68B1" },
  ["idris"] = { t = "programming", c = "#b30000" },
  ["ignore list"] = { t = "data", c = "#000000" },
  ["imagej macro"] = { t = "programming", c = "#99AAFF" },
  ["imba"] = { t = "programming", c = "#16cec6" },
  ["inform 7"] = { t = "programming" },
  ["ink"] = { t = "programming" },
  ["inno setup"] = { t = "programming", c = "#264b99" },
  ["io"] = { t = "programming", c = "#a9188d" },
  ["ioke"] = { t = "programming", c = "#078193" },
  ["isabelle"] = { t = "programming", c = "#FEFE00" },
  ["isabelle root"] = { t = "programming", c = "#FEFE00" },
  ["j"] = { t = "programming", c = "#9EEDFF" },
  ["jar manifest"] = { t = "data", c = "#b07219" },
  ["jcl"] = { t = "programming", c = "#d90e09" },
  ["jflex"] = { t = "programming", c = "#DBCA00" },
  ["json"] = { t = "data", c = "#292929" },
  ["json with comments"] = { t = "data", c = "#292929" },
  ["json5"] = { t = "data", c = "#267CB9" },
  ["jsonld"] = { t = "data", c = "#0c479c" },
  ["jsoniq"] = { t = "programming", c = "#40d47e" },
  ["jac"] = { t = "programming", c = "#FC792D" },
  ["jai"] = { t = "programming", c = "#ab8b4b" },
  ["janet"] = { t = "programming", c = "#0886a5" },
  ["jasmin"] = { t = "programming", c = "#d03600" },
  ["java"] = { t = "programming", c = "#b07219" },
  ["java properties"] = { t = "data", c = "#2A6277" },
  ["java server pages"] = { t = "programming", c = "#2A6277" },
  ["java template engine"] = { t = "programming", c = "#2A6277" },
  ["javascript"] = { t = "programming", c = "#f1e05a" },
  ["javascript+erb"] = { t = "programming", c = "#f1e05a" },
  ["jest snapshot"] = { t = "data", c = "#15c213" },
  ["jetbrains mps"] = { t = "programming", c = "#21D789" },
  ["jinja"] = { t = "markup", c = "#a52a22" },
  ["jison"] = { t = "programming", c = "#56b3cb" },
  ["jison lex"] = { t = "programming", c = "#56b3cb" },
  ["jolie"] = { t = "programming", c = "#843179" },
  ["jsonnet"] = { t = "programming", c = "#0064bd" },
  ["julia"] = { t = "programming", c = "#a270ba" },
  ["julia repl"] = { t = "programming", c = "#a270ba" },
  ["jupyter notebook"] = { t = "markup", c = "#DA5B0B" },
  ["just"] = { t = "programming", c = "#384d54" },
  ["kcl"] = { t = "programming", c = "#7ABABF" },
  ["kdl"] = { t = "data", c = "#ffb3b3" },
  ["kframework"] = { t = "programming", c = "#4195c5" },
  ["krl"] = { t = "programming", c = "#28430A" },
  ["kaitai struct"] = { t = "programming", c = "#773b37" },
  ["kakounescript"] = { t = "programming", c = "#6f8042" },
  ["kerboscript"] = { t = "programming", c = "#41adf0" },
  ["kicad layout"] = { t = "data", c = "#2f4aab" },
  ["kicad legacy layout"] = { t = "data", c = "#2f4aab" },
  ["kicad schematic"] = { t = "data", c = "#2f4aab" },
  ["kickstart"] = { t = "data" },
  ["kit"] = { t = "markup" },
  ["kolmafia ash"] = { t = "programming", c = "#B9D9B9" },
  ["koka"] = { t = "programming", c = "#215166" },
  ["kotlin"] = { t = "programming", c = "#A97BFF" },
  ["kusto"] = { t = "data" },
  ["lfe"] = { t = "programming", c = "#4C3023" },
  ["llvm"] = { t = "programming", c = "#185619" },
  ["lolcode"] = { t = "programming", c = "#cc9900" },
  ["lsl"] = { t = "programming", c = "#3d9970" },
  ["ltspice symbol"] = { t = "data" },
  ["labview"] = { t = "programming", c = "#fede06" },
  ["lambdapi"] = { t = "programming", c = "#8027a3" },
  ["langium"] = { t = "programming", c = "#2c8c87" },
  ["lark"] = { t = "data", c = "#2980B9" },
  ["lasso"] = { t = "programming", c = "#999999" },
  ["latte"] = { t = "markup", c = "#f2a542" },
  ["lean"] = { t = "programming" },
  ["lean 4"] = { t = "programming" },
  ["leo"] = { t = "programming", c = "#C4FFC2" },
  ["less"] = { t = "markup", c = "#1d365d" },
  ["lex"] = { t = "programming", c = "#DBCA00" },
  ["ligolang"] = { t = "programming", c = "#0e74ff" },
  ["lilypond"] = { t = "programming", c = "#9ccc7c" },
  ["limbo"] = { t = "programming" },
  ["linear programming"] = { t = "programming" },
  ["linker script"] = { t = "programming" },
  ["linux kernel module"] = { t = "data" },
  ["liquid"] = { t = "markup", c = "#67b8de" },
  ["liquidsoap"] = { t = "programming", c = "#990066" },
  ["literate agda"] = { t = "programming", c = "#315665" },
  ["literate coffeescript"] = { t = "programming", c = "#244776" },
  ["literate haskell"] = { t = "programming", c = "#5e5086" },
  ["livecode script"] = { t = "programming", c = "#0c5ba5" },
  ["livescript"] = { t = "programming", c = "#499886" },
  ["logos"] = { t = "programming" },
  ["logtalk"] = { t = "programming", c = "#295b9a" },
  ["lookml"] = { t = "programming", c = "#652B81" },
  ["loomscript"] = { t = "programming" },
  ["lua"] = { t = "programming", c = "#000080" },
  ["luau"] = { t = "programming", c = "#00A2FF" },
  ["m"] = { t = "programming" },
  ["m3u"] = { t = "data", c = "#179C7D" },
  ["m4"] = { t = "programming" },
  ["m4sugar"] = { t = "programming" },
  ["matlab"] = { t = "programming", c = "#e16737" },
  ["maxscript"] = { t = "programming", c = "#00a6a6" },
  ["mdx"] = { t = "markup", c = "#fcb32c" },
  ["mlir"] = { t = "programming", c = "#5EC8DB" },
  ["mql4"] = { t = "programming", c = "#62A8D6" },
  ["mql5"] = { t = "programming", c = "#4A76B8" },
  ["mtml"] = { t = "markup", c = "#b7e1f4" },
  ["muf"] = { t = "programming" },
  ["macaulay2"] = { t = "programming", c = "#d8ffff" },
  ["makefile"] = { t = "programming", c = "#427819" },
  ["mako"] = { t = "programming", c = "#7e858d" },
  ["markdown"] = { t = "prose", c = "#083fa1" },
  ["marko"] = { t = "markup", c = "#42bff2" },
  ["mask"] = { t = "markup", c = "#f97732" },
  ["mathematical programming system"] = { t = "programming", c = "#0530ad" },
  ["maven pom"] = { t = "data" },
  ["max"] = { t = "programming", c = "#c4a79c" },
  ["metta"] = { t = "programming", c = "#6a5acd" },
  ["mercury"] = { t = "programming", c = "#ff2b2b" },
  ["mermaid"] = { t = "markup", c = "#ff3670" },
  ["meson"] = { t = "programming", c = "#007800" },
  ["metal"] = { t = "programming", c = "#8f14e9" },
  ["microsoft developer studio project"] = { t = "data" },
  ["microsoft visual studio solution"] = { t = "data" },
  ["minid"] = { t = "programming" },
  ["miniyaml"] = { t = "data", c = "#ff1111" },
  ["minizinc"] = { t = "programming", c = "#06a9e6" },
  ["minizinc data"] = { t = "data" },
  ["mint"] = { t = "programming", c = "#02b046" },
  ["mirah"] = { t = "programming", c = "#c7a938" },
  ["modelica"] = { t = "programming", c = "#de1d31" },
  ["modula-2"] = { t = "programming", c = "#10253f" },
  ["modula-3"] = { t = "programming", c = "#223388" },
  ["module management system"] = { t = "programming" },
  ["mojo"] = { t = "programming", c = "#ff4c1f" },
  ["monkey"] = { t = "programming" },
  ["monkey c"] = { t = "programming", c = "#8D6747" },
  ["moocode"] = { t = "programming" },
  ["moonbit"] = { t = "programming", c = "#b92381" },
  ["moonscript"] = { t = "programming", c = "#ff4585" },
  ["motoko"] = { t = "programming", c = "#fbb03b" },
  ["motorola 68k assembly"] = { t = "programming", c = "#005daa" },
  ["move"] = { t = "programming", c = "#4a137a" },
  ["muse"] = { t = "prose" },
  ["mustache"] = { t = "markup", c = "#724b3b" },
  ["myghty"] = { t = "programming" },
  ["nasl"] = { t = "programming" },
  ["ncl"] = { t = "programming", c = "#28431f" },
  ["neon"] = { t = "data" },
  ["nl"] = { t = "data" },
  ["nmodl"] = { t = "programming", c = "#00356B" },
  ["npm config"] = { t = "data", c = "#cb3837" },
  ["nsis"] = { t = "programming" },
  ["nwscript"] = { t = "programming", c = "#111522" },
  ["nasal"] = { t = "programming", c = "#1d2c4e" },
  ["nearley"] = { t = "programming", c = "#990000" },
  ["nemerle"] = { t = "programming", c = "#3d3c6e" },
  ["netlinx"] = { t = "programming", c = "#0aa0ff" },
  ["netlinx+erb"] = { t = "programming", c = "#747faa" },
  ["netlogo"] = { t = "programming", c = "#ff6375" },
  ["newlisp"] = { t = "programming", c = "#87AED7" },
  ["nextflow"] = { t = "programming", c = "#3ac486" },
  ["nginx"] = { t = "data", c = "#009639" },
  ["nickel"] = { t = "programming", c = "#E0C3FC" },
  ["nim"] = { t = "programming", c = "#ffc200" },
  ["ninja"] = { t = "data" },
  ["nit"] = { t = "programming", c = "#009917" },
  ["nix"] = { t = "programming", c = "#7e7eff" },
  ["noir"] = { t = "programming", c = "#2f1f49" },
  ["nu"] = { t = "programming", c = "#c9df40" },
  ["numpy"] = { t = "programming", c = "#9C8AF9" },
  ["nunjucks"] = { t = "markup", c = "#3d8137" },
  ["nushell"] = { t = "programming", c = "#4E9906" },
  ["oasv2-json"] = { t = "data", c = "#85ea2d" },
  ["oasv2-yaml"] = { t = "data", c = "#85ea2d" },
  ["oasv3-json"] = { t = "data", c = "#85ea2d" },
  ["oasv3-yaml"] = { t = "data", c = "#85ea2d" },
  ["ocaml"] = { t = "programming", c = "#ef7a08" },
  ["omnet++ msg"] = { t = "programming", c = "#a0e0a0" },
  ["omnet++ ned"] = { t = "programming", c = "#08607c" },
  ["oberon"] = { t = "programming" },
  ["objdump"] = { t = "data" },
  ["object data instance notation"] = { t = "data" },
  ["objectscript"] = { t = "programming", c = "#424893" },
  ["objective-c"] = { t = "programming", c = "#438eff" },
  ["objective-c++"] = { t = "programming", c = "#6866fb" },
  ["objective-j"] = { t = "programming", c = "#ff0c5a" },
  ["odin"] = { t = "programming", c = "#60AFFE" },
  ["omgrofl"] = { t = "programming", c = "#cabbff" },
  ["opa"] = { t = "programming" },
  ["opal"] = { t = "programming", c = "#f7ede0" },
  ["open policy agent"] = { t = "programming", c = "#7d9199" },
  ["openapi specification v2"] = { t = "data", c = "#85ea2d" },
  ["openapi specification v3"] = { t = "data", c = "#85ea2d" },
  ["opencl"] = { t = "programming", c = "#ed2e2d" },
  ["openedge abl"] = { t = "programming", c = "#5ce600" },
  ["openqasm"] = { t = "programming", c = "#AA70FF" },
  ["openrc runscript"] = { t = "programming" },
  ["openscad"] = { t = "programming", c = "#e5cd45" },
  ["openstep property list"] = { t = "data" },
  ["opentype feature file"] = { t = "data" },
  ["option list"] = { t = "data", c = "#476732" },
  ["org"] = { t = "prose", c = "#77aa99" },
  ["overpy"] = { t = "programming", c = "#78b355" },
  ["overpassql"] = { t = "programming", c = "#cce2aa" },
  ["ox"] = { t = "programming" },
  ["oxygene"] = { t = "programming", c = "#cdd0e3" },
  ["oz"] = { t = "programming", c = "#fab738" },
  ["p4"] = { t = "programming", c = "#7055b5" },
  ["pddl"] = { t = "programming", c = "#0d00ff" },
  ["peg.js"] = { t = "programming", c = "#234d6b" },
  ["php"] = { t = "programming", c = "#4F5D95" },
  ["plsql"] = { t = "programming", c = "#dad8d8" },
  ["plpgsql"] = { t = "programming", c = "#336790" },
  ["pov-ray sdl"] = { t = "programming", c = "#6bac65" },
  ["pact"] = { t = "programming", c = "#F7A8B8" },
  ["pan"] = { t = "programming", c = "#cc0000" },
  ["papyrus"] = { t = "programming", c = "#6600cc" },
  ["parrot"] = { t = "programming", c = "#f3ca0a" },
  ["parrot assembly"] = { t = "programming" },
  ["parrot internal representation"] = { t = "programming" },
  ["pascal"] = { t = "programming", c = "#E3F171" },
  ["pawn"] = { t = "programming", c = "#dbb284" },
  ["pep8"] = { t = "programming", c = "#C76F5B" },
  ["perl"] = { t = "programming", c = "#0298c3" },
  ["pic"] = { t = "markup" },
  ["pickle"] = { t = "data" },
  ["picolisp"] = { t = "programming", c = "#6067af" },
  ["piglatin"] = { t = "programming", c = "#fcd7de" },
  ["pike"] = { t = "programming", c = "#005390" },
  ["pip requirements"] = { t = "data", c = "#FFD343" },
  ["pkl"] = { t = "programming", c = "#6b9543" },
  ["plantuml"] = { t = "data", c = "#fbbd16" },
  ["pod"] = { t = "prose" },
  ["pod 6"] = { t = "prose" },
  ["pogoscript"] = { t = "programming", c = "#d80074" },
  ["polar"] = { t = "programming", c = "#ae81ff" },
  ["pony"] = { t = "programming" },
  ["portugol"] = { t = "programming", c = "#f8bd00" },
  ["postcss"] = { t = "markup", c = "#dc3a0c" },
  ["postscript"] = { t = "markup", c = "#da291c" },
  ["powerbuilder"] = { t = "programming", c = "#8f0f8d" },
  ["powershell"] = { t = "programming", c = "#012456" },
  ["praat"] = { t = "programming", c = "#c8506d" },
  ["prisma"] = { t = "data", c = "#0c344b" },
  ["pro*c"] = { t = "programming", c = "#bb8368" },
  ["processing"] = { t = "programming", c = "#0096D8" },
  ["procfile"] = { t = "programming", c = "#3B2F63" },
  ["proguard"] = { t = "data" },
  ["prolog"] = { t = "programming", c = "#74283c" },
  ["promela"] = { t = "programming", c = "#de0000" },
  ["propeller spin"] = { t = "programming", c = "#7fa2a7" },
  ["protocol buffer"] = { t = "data" },
  ["protocol buffer text format"] = { t = "data" },
  ["public key"] = { t = "data" },
  ["pug"] = { t = "markup", c = "#a86454" },
  ["puppet"] = { t = "programming", c = "#302B6D" },
  ["pure data"] = { t = "data" },
  ["purebasic"] = { t = "programming", c = "#5a6986" },
  ["purescript"] = { t = "programming", c = "#1D222D" },
  ["pyret"] = { t = "programming", c = "#ee1e10" },
  ["python"] = { t = "programming", c = "#3572A5" },
  ["python console"] = { t = "programming", c = "#3572A5" },
  ["python traceback"] = { t = "data", c = "#3572A5" },
  ["q#"] = { t = "programming", c = "#fed659" },
  ["qml"] = { t = "programming", c = "#44a51c" },
  ["qmake"] = { t = "programming" },
  ["qt script"] = { t = "programming", c = "#00b841" },
  ["quake"] = { t = "programming", c = "#882233" },
  ["quakec"] = { t = "programming", c = "#975777" },
  ["quickbasic"] = { t = "programming", c = "#008080" },
  ["quint"] = { t = "programming", c = "#9d6ce5" },
  ["r"] = { t = "programming", c = "#198CE7" },
  ["raml"] = { t = "markup", c = "#77d9fb" },
  ["rascript"] = { t = "programming", c = "#2C97FA" },
  ["rbs"] = { t = "data", c = "#701516" },
  ["rdoc"] = { t = "prose", c = "#701516" },
  ["realbasic"] = { t = "programming" },
  ["rexx"] = { t = "programming", c = "#d90e09" },
  ["rmarkdown"] = { t = "prose", c = "#198ce7" },
  ["ron"] = { t = "data", c = "#a62c00" },
  ["ros interface"] = { t = "data", c = "#22314e" },
  ["rpc"] = { t = "programming" },
  ["rpgle"] = { t = "programming", c = "#2BDE21" },
  ["rpm spec"] = { t = "data" },
  ["runoff"] = { t = "markup", c = "#665a4e" },
  ["racket"] = { t = "programming", c = "#3c5caa" },
  ["ragel"] = { t = "programming", c = "#9d5200" },
  ["raku"] = { t = "programming", c = "#0000fb" },
  ["rascal"] = { t = "programming", c = "#fffaa0" },
  ["raw token data"] = { t = "data" },
  ["rescript"] = { t = "programming", c = "#ed5051" },
  ["readline config"] = { t = "data" },
  ["reason"] = { t = "programming", c = "#ff5847" },
  ["reasonligo"] = { t = "programming", c = "#ff5847" },
  ["rebol"] = { t = "programming", c = "#358a5b" },
  ["record jar"] = { t = "data", c = "#0673ba" },
  ["red"] = { t = "programming", c = "#f50000" },
  ["redcode"] = { t = "programming" },
  ["redirect rules"] = { t = "data" },
  ["redscript"] = { t = "programming", c = "#f44336" },
  ["regular expression"] = { t = "data", c = "#009a00" },
  ["ren'py"] = { t = "programming", c = "#ff7f7f" },
  ["renderscript"] = { t = "programming" },
  ["rez"] = { t = "programming", c = "#FFDAB3" },
  ["rich text format"] = { t = "markup" },
  ["ring"] = { t = "programming", c = "#2D54CB" },
  ["riot"] = { t = "markup", c = "#A71E49" },
  ["robotframework"] = { t = "programming", c = "#00c0b5" },
  ["robots exclusion rules"] = { t = "data" },
  ["roc"] = { t = "programming", c = "#7c38f5" },
  ["rocq prover"] = { t = "programming", c = "#d0b68c" },
  ["roff"] = { t = "markup", c = "#ecdebe" },
  ["roff manpage"] = { t = "markup", c = "#ecdebe" },
  ["rouge"] = { t = "programming", c = "#cc0088" },
  ["routeros script"] = { t = "programming", c = "#DE3941" },
  ["ruby"] = { t = "programming", c = "#701516" },
  ["rust"] = { t = "programming", c = "#dea584" },
  ["sas"] = { t = "programming", c = "#B34936" },
  ["scss"] = { t = "markup", c = "#c6538c" },
  ["selinux policy"] = { t = "data" },
  ["smt"] = { t = "programming" },
  ["sparql"] = { t = "data", c = "#0C4597" },
  ["sqf"] = { t = "programming", c = "#3F3F3F" },
  ["sql"] = { t = "data", c = "#e38c00" },
  ["sqlpl"] = { t = "programming", c = "#e38c00" },
  ["srecode template"] = { t = "markup", c = "#348a34" },
  ["ssh config"] = { t = "data" },
  ["star"] = { t = "data" },
  ["stl"] = { t = "data", c = "#373b5e" },
  ["ston"] = { t = "data" },
  ["svg"] = { t = "data", c = "#ff9900" },
  ["swig"] = { t = "programming" },
  ["sage"] = { t = "programming" },
  ["sail"] = { t = "programming", c = "#259dd5" },
  ["saltstack"] = { t = "programming", c = "#646464" },
  ["sass"] = { t = "markup", c = "#a53b70" },
  ["scala"] = { t = "programming", c = "#c22d40" },
  ["scaml"] = { t = "markup", c = "#bd181a" },
  ["scenic"] = { t = "programming", c = "#fdc700" },
  ["scheme"] = { t = "programming", c = "#1e4aec" },
  ["scilab"] = { t = "programming", c = "#ca0f21" },
  ["self"] = { t = "programming", c = "#0579aa" },
  ["shaderlab"] = { t = "programming", c = "#222c37" },
  ["shell"] = { t = "programming", c = "#89e051" },
  ["shellcheck config"] = { t = "data", c = "#cecfcb" },
  ["shellsession"] = { t = "programming" },
  ["shen"] = { t = "programming", c = "#120F14" },
  ["sieve"] = { t = "programming" },
  ["simple file verification"] = { t = "data", c = "#C9BFED" },
  ["singularity"] = { t = "programming", c = "#64E6AD" },
  ["slang"] = { t = "programming", c = "#1fbec9" },
  ["slash"] = { t = "programming", c = "#007eff" },
  ["slice"] = { t = "programming", c = "#003fa2" },
  ["slim"] = { t = "markup", c = "#2b2b2b" },
  ["slint"] = { t = "markup", c = "#2379F4" },
  ["smpl"] = { t = "programming", c = "#c94949" },
  ["smali"] = { t = "programming" },
  ["smalltalk"] = { t = "programming", c = "#596706" },
  ["smarty"] = { t = "programming", c = "#f0c040" },
  ["smithy"] = { t = "programming", c = "#c44536" },
  ["snakemake"] = { t = "programming", c = "#419179" },
  ["solidity"] = { t = "programming", c = "#AA6746" },
  ["soong"] = { t = "data" },
  ["sourcepawn"] = { t = "programming", c = "#f69e1d" },
  ["spicedb schema"] = { t = "data", c = "#a5318a" },
  ["spline font database"] = { t = "data" },
  ["squirrel"] = { t = "programming", c = "#800000" },
  ["stan"] = { t = "programming", c = "#b2011d" },
  ["standard ml"] = { t = "programming", c = "#dc566d" },
  ["starlark"] = { t = "programming", c = "#76d275" },
  ["stata"] = { t = "programming", c = "#1a5f91" },
  ["stringtemplate"] = { t = "markup", c = "#3fb34f" },
  ["stylus"] = { t = "markup", c = "#ff6347" },
  ["subrip text"] = { t = "data", c = "#9e0101" },
  ["sugarss"] = { t = "markup", c = "#2fcc9f" },
  ["supercollider"] = { t = "programming", c = "#46390b" },
  ["surrealql"] = { t = "programming", c = "#ff00a0" },
  ["survex data"] = { t = "data", c = "#ffcc99" },
  ["svelte"] = { t = "markup", c = "#ff3e00" },
  ["sway"] = { t = "programming", c = "#00F58C" },
  ["sweave"] = { t = "prose", c = "#198ce7" },
  ["swift"] = { t = "programming", c = "#F05138" },
  ["systemverilog"] = { t = "programming", c = "#DAE1C2" },
  ["ti program"] = { t = "programming", c = "#A0AA87" },
  ["tl-verilog"] = { t = "programming", c = "#C40023" },
  ["tla"] = { t = "programming", c = "#4b0079" },
  ["tmdl"] = { t = "data", c = "#f0c913" },
  ["toml"] = { t = "data", c = "#9c4221" },
  ["tsplib data"] = { t = "data" },
  ["tsql"] = { t = "programming", c = "#e38c00" },
  ["tsv"] = { t = "data", c = "#237346" },
  ["tsx"] = { t = "programming", c = "#3178c6" },
  ["txl"] = { t = "programming", c = "#0178b8" },
  ["tact"] = { t = "programming", c = "#48b5ff" },
  ["talon"] = { t = "programming", c = "#333333" },
  ["tcl"] = { t = "programming", c = "#e4cc98" },
  ["tcsh"] = { t = "programming" },
  ["tex"] = { t = "markup", c = "#3D6117" },
  ["tea"] = { t = "markup" },
  ["teal"] = { t = "programming", c = "#00B1BC" },
  ["terra"] = { t = "programming", c = "#00004c" },
  ["terraform template"] = { t = "markup", c = "#7b42bb" },
  ["texinfo"] = { t = "prose" },
  ["text"] = { t = "prose" },
  ["textgrid"] = { t = "data", c = "#c8506d" },
  ["textmate properties"] = { t = "data", c = "#df66e4" },
  ["textile"] = { t = "prose", c = "#ffe7ac" },
  ["thrift"] = { t = "programming", c = "#D12127" },
  ["toit"] = { t = "programming", c = "#c2c9fb" },
  ["tor config"] = { t = "data", c = "#59316b" },
  ["tree-sitter query"] = { t = "programming", c = "#8ea64c" },
  ["turing"] = { t = "programming", c = "#cf142b" },
  ["turtle"] = { t = "data" },
  ["twig"] = { t = "markup", c = "#c1d026" },
  ["type language"] = { t = "data" },
  ["typescript"] = { t = "programming", c = "#3178c6" },
  ["typespec"] = { t = "programming", c = "#4A3665" },
  ["typst"] = { t = "programming", c = "#239dad" },
  ["unified parallel c"] = { t = "programming", c = "#4e3617" },
  ["unity3d asset"] = { t = "data", c = "#222c37" },
  ["unix assembly"] = { t = "programming" },
  ["uno"] = { t = "programming", c = "#9933cc" },
  ["unrealscript"] = { t = "programming", c = "#a54c4d" },
  ["untyped plutus core"] = { t = "programming", c = "#36adbd" },
  ["urweb"] = { t = "programming", c = "#ccccee" },
  ["v"] = { t = "programming", c = "#4f87c4" },
  ["vba"] = { t = "programming", c = "#867db1" },
  ["vbscript"] = { t = "programming", c = "#15dcdc" },
  ["vcl"] = { t = "programming", c = "#148AA8" },
  ["vhdl"] = { t = "programming", c = "#adb2cb" },
  ["vala"] = { t = "programming", c = "#a56de2" },
  ["valve data format"] = { t = "data", c = "#f26025" },
  ["velocity template language"] = { t = "markup", c = "#507cff" },
  ["vento"] = { t = "markup", c = "#ff0080" },
  ["verilog"] = { t = "programming", c = "#b2b7f8" },
  ["vim help file"] = { t = "prose", c = "#199f4b" },
  ["vim script"] = { t = "programming", c = "#199f4b" },
  ["vim snippet"] = { t = "markup", c = "#199f4b" },
  ["visual basic .net"] = { t = "programming", c = "#945db7" },
  ["visual basic 6.0"] = { t = "programming", c = "#2c6353" },
  ["volt"] = { t = "programming", c = "#1F1F1F" },
  ["vue"] = { t = "markup", c = "#41b883" },
  ["vyper"] = { t = "programming", c = "#9F4CF2" },
  ["wdl"] = { t = "programming", c = "#42f1f4" },
  ["wgsl"] = { t = "programming", c = "#1a5e9a" },
  ["wavefront material"] = { t = "data" },
  ["wavefront object"] = { t = "data" },
  ["web ontology language"] = { t = "data", c = "#5b70bd" },
  ["webassembly"] = { t = "programming", c = "#04133b" },
  ["webassembly interface type"] = { t = "data", c = "#6250e7" },
  ["webidl"] = { t = "programming" },
  ["webvtt"] = { t = "data" },
  ["wget config"] = { t = "data" },
  ["whiley"] = { t = "programming", c = "#d5c397" },
  ["wikitext"] = { t = "prose", c = "#fc5757" },
  ["win32 message file"] = { t = "data" },
  ["windows registry entries"] = { t = "data", c = "#52d5ff" },
  ["witcher script"] = { t = "programming", c = "#ff0000" },
  ["wolfram language"] = { t = "programming", c = "#dd1100" },
  ["wollok"] = { t = "programming", c = "#a23738" },
  ["world of warcraft addon data"] = { t = "data", c = "#f7e43f" },
  ["wren"] = { t = "programming", c = "#383838" },
  ["x bitmap"] = { t = "data" },
  ["x font directory index"] = { t = "data" },
  ["x pixmap"] = { t = "data" },
  ["x10"] = { t = "programming", c = "#4B6BEF" },
  ["xc"] = { t = "programming", c = "#99DA07" },
  ["xcompose"] = { t = "data" },
  ["xml"] = { t = "data", c = "#0060ac" },
  ["xml property list"] = { t = "data", c = "#0060ac" },
  ["xpages"] = { t = "data" },
  ["xproc"] = { t = "programming" },
  ["xquery"] = { t = "programming", c = "#5232e7" },
  ["xs"] = { t = "programming" },
  ["xslt"] = { t = "programming", c = "#EB8CEB" },
  ["xmake"] = { t = "programming", c = "#22a079" },
  ["xojo"] = { t = "programming", c = "#81bd41" },
  ["xonsh"] = { t = "programming", c = "#285EEF" },
  ["xtend"] = { t = "programming", c = "#24255d" },
  ["yaml"] = { t = "data", c = "#cb171e" },
  ["yang"] = { t = "data" },
  ["yara"] = { t = "programming", c = "#220000" },
  ["yasnippet"] = { t = "markup", c = "#32AB90" },
  ["yacc"] = { t = "programming", c = "#4B6C4B" },
  ["yul"] = { t = "programming", c = "#794932" },
  ["zap"] = { t = "programming", c = "#0d665e" },
  ["zil"] = { t = "programming", c = "#dc75e5" },
  ["zeek"] = { t = "programming" },
  ["zenscript"] = { t = "programming", c = "#00BCD1" },
  ["zephir"] = { t = "programming", c = "#118f9e" },
  ["zig"] = { t = "programming", c = "#ec915c" },
  ["zimpl"] = { t = "programming", c = "#d67711" },
  ["zmodel"] = { t = "data", c = "#ff7100" },
  ["curl config"] = { t = "data" },
  ["crontab"] = { t = "data", c = "#ead7ac" },
  ["desktop"] = { t = "data" },
  ["dircolors"] = { t = "data" },
  ["ec"] = { t = "programming", c = "#913960" },
  ["edn"] = { t = "data" },
  ["fish"] = { t = "programming", c = "#4aae47" },
  ["hoon"] = { t = "programming", c = "#00b171" },
  ["icalendar"] = { t = "data", c = "#ec564c" },
  ["jq"] = { t = "programming", c = "#c7254e" },
  ["kvlang"] = { t = "markup", c = "#1da6e0" },
  ["mirc script"] = { t = "programming", c = "#3d57c3" },
  ["mcfunction"] = { t = "programming", c = "#E22837" },
  ["mdsvex"] = { t = "markup", c = "#5f9ea0" },
  ["mupad"] = { t = "programming", c = "#244963" },
  ["nanorc"] = { t = "data", c = "#2d004d" },
  ["nesc"] = { t = "programming", c = "#94B0C7" },
  ["ooc"] = { t = "programming", c = "#b0b77e" },
  ["pkg-config"] = { t = "data", c = "#2b5e82" },
  ["q"] = { t = "programming", c = "#0040cd" },
  ["restructuredtext"] = { t = "prose", c = "#141414" },
  ["sed"] = { t = "programming", c = "#64b970" },
  ["templ"] = { t = "markup", c = "#66D0DD" },
  ["vcard"] = { t = "data", c = "#ee2647" },
  ["wisp"] = { t = "programming", c = "#7582D1" },
  ["xbase"] = { t = "programming", c = "#403a40" },
}
